server:
  port: 9999
logging:
  level:
    org.springframework: debug
    com.yc: debug

#  保证consumer能服务发现
eureka:
  client:
    register-with-eureka: false    #消费端不须要到eureka中注册
    service-url:
      defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka


feign:
  compression:
    request:
      enabled: true
      mime-types: # 可以被压缩的类型
        - text/xml
        - application/xml
        - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩
  hystrix:
      enabled: true

