server:
  port: 7201
spring:
  cloud:
    config:
      server:
        git:     #git服务器配置
          uri: https://github.com/zhangyingchengqi/microservice_config.git
          label: main
    bus:     # 开启bus消息总线
      trace:
        enabled: true

    stream:
      kafka:
        binder:
          brokers: 39.99.175.175

  #  rabbitmq:
  #    host: localhost
  #    port: 5672    # RabbitMQ的监听端口
  #    username: zy  # 用户名
  #    password: a # 密码
  application:
    name: microservice-config-bus

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:a@localhost:7301/eureka
  instance:
    prefer-ip-address: true # 在地址栏上使用IP地址进行显示
    instance-id: microservice-config-bus
management:
  endpoints:
    web:
      exposure:
        include: "*"